const { ObjectId } = require('mongodb');
const {
  convertImageToBase64,
  generateVideoFromImage,
  checkVideoTaskStatus,
  saveVideoTask,
  pollVideoTaskStatus,
} = require('../models/img2video-utils');
const {
    getUserVideoPrompt
} = require('../models/chat-tool-settings-utils');
const { generateCompletion } = require('../models/openai')
const { removeUserPoints } = require('../models/user-points-utils');
/**
 * Image to Video API Routes
 * @param {Object} fastify - Fastify instance
 */
async function img2videoRoutes(fastify) {

    /**
     * POST /api/img2video/generate
     * Generate video from image
     */
    fastify.post('/api/img2video/generate', async (request, reply) => {
        console.log('[img2video] POST /api/img2video/generate called');
        try {
            const { imageId, prompt, chatId, userChatId, placeholderId } = request.body;
            const userId = request?.user?._id;
            console.log(`[img2video] Request body:`, request.body);
            console.log(`[img2video] User ID: ${userId}`);

            if (!userId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            if (!imageId || !chatId || !placeholderId) {
                console.warn('[img2video] Missing required parameters', { imageId, chatId, placeholderId });
                return reply.status(400).send({ error: 'Missing required parameters' });
            }

            const db = fastify.mongo.db;

            // Charge points for video generation
            const cost = 100; // Define the cost of generating an image
            console.log(`[img2video] Cost for video generation: ${cost} points`);
            try {
                await removeUserPoints(db, userId, cost, translations.points?.deduction_reasons?.video_generation || 'Video generation', 'video_generation', fastify);
            } catch (error) {
                console.error('Error deducting points:', error);
                return reply.status(500).send({ error: 'Error deducting points for video generation.' });
            }

            // Check if a task with this placeholderId already exists
            const existingPlaceholderTask = await db.collection('tasks').findOne({
                placeholderId: placeholderId,
                type: 'img2video',
                status: { $in: ['pending', 'processing', 'background'] }
            });
            
            if (existingPlaceholderTask) {
                console.warn(`[img2video] Task with placeholderId already exists: ${placeholderId}`);
                return reply.status(429).send({ error: 'Task with this placeholder already in progress' });
            }

            // Check if a video is already being generated by the user for this image
            const existingTask = await db.collection('tasks').findOne({
                userId: new ObjectId(userId),
                imageId: new ObjectId(imageId),
                type: 'img2video',
                status: { $in: ['pending', 'processing', 'background'] }
            });
            if (existingTask) {
                console.warn(`[img2video] User already has a video generation task for this image: ${existingTask.taskId}`);
                fastify.sendNotificationToUser(userId, 'showNotification', {
                    icon: 'warning',
                    message: request.img2videoTranslations?.notifications?.alreadyInProgress || 'You already have a video generation task in progress for this image.'
                });
                return reply.status(429).send({ error: 'Video generation already in progress for this image' });
            }

            // [DEBUG] Currently only the image generated by the user is supported
            const gallery = await db.collection('gallery').findOne(
                { 
                    chatId: new ObjectId(chatId), 
                    userId: new ObjectId(userId) 
                });

            if (!gallery || !Array.isArray(gallery.images)) {
                console.warn(`[img2video] Gallery not found for chatId: ${chatId}, userId: ${userId}`);
                return reply.status(404).send({ error: 'Gallery not found' });
            }
            const image = gallery.images.find(img => img._id && img._id.toString() === imageId.toString());
            if (!image) {
                console.error(`[img2video] Image with ID ${imageId} not found in gallery for chatId: ${chatId}`);
                return reply.status(404).send({ error: 'Image not found' });
            }
            console.log(`[img2video] Image found: ${image.imageUrl}`);

            try {
                const imageUrl = image.imageUrl;
                console.log(`[img2video] Starting video generation for imageUrl: ${imageUrl}`);
                const systemPrompt = [
                    {
                        role: 'system',
                        content: `You are an AI assistant that generates videos prompt from an image prompt.
                                  Use the provided image prompt to create a dynamic video prompt. 
                                  Ensure the video prompt is engaging and visually appealing.
                                  Your response should be a clear and concise instruction for the video generation process.
                                  Your role is to describe the video content, style, and any specific elements that should be included.
                                  Do not include any additional text or explanations, just the video prompt.
                                  `
                    },
                    {
                        role: 'user',
                        content: `Here is a description of the image: ${image.prompt || 'No description provided'}`
                    }
                ]
                // Add user defaul prompt if available
                const userVideoPrompt = await getUserVideoPrompt(fastify.mongo.db, userId, chatId);
                if (userVideoPrompt && userVideoPrompt.trim() !== '') {
                    systemPrompt.push({
                        role: 'user',
                        content: `Use the following user-defined video prompt as a base: ${userVideoPrompt}`
                    });
                }
                if( prompt && prompt.trim() !== '' ) {
                    systemPrompt.push({
                        role: 'user',
                        content:`Here is the desired video: ${prompt}`
                    });
                }
                const instructionPrompt = await generateCompletion(systemPrompt, 600, 'mistral');
                console.log(`[img2video] Generated instruction prompt: ${instructionPrompt}`);

                // Start video generation
                const videoTask = await generateVideoFromImage({
                    imageUrl,
                    prompt: instructionPrompt,
                    userId,
                    chatId,
                    placeholderId
                });

                console.log(`[img2video] Video task response:`, videoTask);

                if (!videoTask.success) {
                    console.error(`[img2video] Failed to start video generation: ${videoTask.message}`);
                    throw new Error(videoTask.message || 'Failed to start video generation');
                }

                // Save task to database
                await saveVideoTask({
                    taskId: videoTask.taskId,
                    userId,
                    chatId,
                    userChatId,
                    imageId,
                    imageUrl: image.imageUrl,
                    prompt: prompt || image.prompt,
                    placeholderId,
                    fastify
                });
                console.log(`[img2video] Video task saved to DB: ${videoTask.taskId}`);

                // Start polling for task completion in background
                pollVideoTaskStatus(videoTask.taskId, fastify, {
                    userId,
                    chatId,
                    userChatId,
                    placeholderId,
                    imageId,
                    prompt: prompt || image.prompt
                });
                console.log(`[img2video] Started polling for video task: ${videoTask.taskId}`);

                return reply.send({
                    success: true,
                    taskId: videoTask.taskId,
                    placeholderId,
                    message: 'Video generation started'
                });

            } catch (error) {
                console.error('Error processing video generation:', error);
                return reply.status(500).send({ error: error.message });
            }

        } catch (error) {
            console.error('Error in img2video generate route:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });

    /**
     * GET /api/img2video/task-status/:taskId
     * Check video generation task status
     */
    fastify.get('/api/img2video/task-status/:taskId', async (request, reply) => {
        console.log('[img2video] GET /api/img2video/task-status/:taskId called');
        try {
            const { taskId } = request.params;
            const userId = request?.user?._id;
            console.log(`[img2video] Checking status for taskId: ${taskId}, userId: ${userId}`);

            if (!userId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            const db = fastify.mongo.db;
            const task = await db.collection('tasks').findOne({ 
                taskId,
                userId: new ObjectId(userId),
                type: 'img2video'
            });

            if (!task) {
                console.warn(`[img2video] Task not found: ${taskId}`);
                return reply.status(404).send({ error: 'Task not found' });
            }

            // If task is completed, return from database
            if (task.status === 'completed') {
                console.log(`[img2video] Task completed: ${taskId}`);
                return reply.send({
                    status: 'completed',
                    result: task.result,
                    userChatId: task.userChatId
                });
            }

            // If task is still processing, check with Novita API
            if (task.status === 'pending' || task.status === 'processing' || task.status === 'background') {
                console.log(`[img2video] Task is ${task.status}, checking external status...`);
                const taskStatus = await checkVideoTaskStatus(taskId);
                console.log(`[img2video] External task status:`, taskStatus);
                
                // Update task status in database
                await db.collection('tasks').updateOne(
                    { taskId },
                    { $set: { status: taskStatus.status, updatedAt: new Date() } }
                );

                return reply.send({
                    status: taskStatus.status,
                    progress: taskStatus.progress,
                    result: taskStatus.result,
                    userChatId: task.userChatId,
                    error: taskStatus.error
                });
            }

            console.log(`[img2video] Returning task status: ${task.status}`);
            return reply.send({
                status: task.status,
                result: task.result,
                userChatId: task.userChatId,
                error: task.result?.error
            });

        } catch (error) {
            console.error('Error checking video task status:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });

    /**
     * GET /api/background-video-tasks/:userChatId
     * Get background video tasks for a specific user chat
     */
    fastify.get('/api/background-video-tasks/:userChatId', async (request, reply) => {
        console.log('[img2video] GET /api/background-video-tasks/:userChatId called');
        try {
            const { userChatId } = request.params;
            const userId = request?.user?._id;
            console.log(`[img2video] Fetching background tasks for userChatId: ${userChatId}, userId: ${userId}`);

            if (!userId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            const db = fastify.mongo.db;
            const tasks = await db.collection('tasks').find({
                userId: new ObjectId(userId),
                userChatId,
                type: 'img2video',
                status: { $in: ['pending', 'processing', 'background'] }
            }).toArray();

            console.log(`[img2video] Found ${tasks.length} background tasks`);
            return reply.send({ tasks });

        } catch (error) {
            console.error('Error fetching background video tasks:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });

    /**
     * GET /api/user-videos/:userId
     * Get user's generated videos
     */
    fastify.get('/api/user-videos/:userId', async (request, reply) => {
        console.log('[img2video] GET /api/user-videos/:userId called');
        try {
            const { userId: targetUserId } = request.params;
            const currentUserId = request?.user?._id;
            const { page = 1, limit = 20 } = request.query;
            console.log(`[img2video] Fetching videos for userId: ${targetUserId}, requested by: ${currentUserId}, page: ${page}, limit: ${limit}`);

            if (!currentUserId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            // Users can only access their own videos unless they're admin
            if (targetUserId !== currentUserId && !request?.user?.isAdmin) {
                console.warn(`[img2video] Access denied for userId: ${currentUserId} to userId: ${targetUserId}`);
                return reply.status(403).send({ error: 'Access denied' });
            }

            const db = fastify.mongo.db;
            const skip = (page - 1) * limit;

            const videos = await db.collection('videos')
                .find({ userId: new ObjectId(targetUserId) })
                .sort({ createdAt: -1 })
                .skip(skip)
                .limit(parseInt(limit))
                .toArray();

            const total = await db.collection('videos').countDocuments({ userId: new ObjectId(targetUserId) });

            console.log(`[img2video] Returning ${videos.length} videos, total: ${total}`);
            return reply.send({
                videos,
                pagination: {
                    page: parseInt(page),
                    limit: parseInt(limit),
                    total,
                    pages: Math.ceil(total / limit)
                }
            });

        } catch (error) {
            console.error('Error fetching user videos:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });

    /**
     * DELETE /api/video/:videoId
     * Delete a generated video
     */
    fastify.delete('/api/video/:videoId', async (request, reply) => {
        console.log('[img2video] DELETE /api/video/:videoId called');
        try {
            const { videoId } = request.params;
            const userId = request?.user?._id;
            console.log(`[img2video] Deleting videoId: ${videoId}, userId: ${userId}`);

            if (!userId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            const db = fastify.mongo.db;
            const video = await db.collection('videos').findOne({ 
                _id: new ObjectId(videoId),
                userId: new ObjectId(userId)
            });

            if (!video) {
                console.warn(`[img2video] Video not found: ${videoId}`);
                return reply.status(404).send({ error: 'Video not found' });
            }

            await db.collection('videos').deleteOne({ _id: new ObjectId(videoId) });
            console.log(`[img2video] Video deleted: ${videoId}`);

            return reply.send({ success: true, message: 'Video deleted successfully' });

        } catch (error) {
            console.error('Error deleting video:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });

    /**
     * GET /api/video/:videoId
     * Get video data by ID
     */
    fastify.get('/api/video/:videoId', async (request, reply) => {
        console.log('[img2video] GET /api/video/:videoId called');
        try {
            const { videoId } = request.params;
            const userId = request?.user?._id;
            console.log(`[img2video] Fetching videoId: ${videoId}, userId: ${userId}`);

            if (!userId) {
                console.warn('[img2video] Unauthorized access attempt');
                return reply.status(401).send({ error: 'Unauthorized' });
            }

            const db = fastify.mongo.db;
            
            // Find video in videos collection
            let video;
            try {
                video = await db.collection('videos').findOne({ 
                    _id: new ObjectId(videoId)
                });
                if (!video) {
                    try {
                        // If not found, check tasks collection
                        video = await db.collection('videos').findOne({ 
                            taskId: videoId,
                        });
                        if (!video) {
                            console.warn(`[img2video] Video task not found: ${videoId}`);
                            return reply.status(404).send({ error: 'Video task not found' });
                        }
                    }
                    catch (error) {
                        console.error(`[img2video] Error fetching video task: ${error.message}`);
                        return reply.status(500).send({ error: 'Internal server error' });
                    }
                }
            } catch (error) {
                
            }
            // Check if user has access to this video (owner or through chat access)
            const hasAccess = video.userId.toString() === userId.toString() || 
                                             await db.collection('userChats').findOne({
                                                 _id: new ObjectId(video.userChatId),
                                                 userId: new ObjectId(userId)
                                             });

            if (!hasAccess) {
                console.warn(`[img2video] Access denied for userId: ${userId} to videoId: ${videoId}`);
                return reply.status(403).send({ error: 'Access denied' });
            }

            return reply.send({
                videoId: video._id,
                videoUrl: video.videoUrl,
                duration: video.duration,
                prompt: video.prompt,
                createdAt: video.createdAt,
                imageId: video.imageId
            });

        } catch (error) {
            console.error('Error fetching video:', error);
            return reply.status(500).send({ error: 'Internal server error' });
        }
    });
}

module.exports = img2videoRoutes;
